server:
  port: 8080

---

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/banking?serverTimezone=UTC&useSSL=false&autoReconnect=true
    username: admin
    password: admin
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect